/*
 * generated by Xtext
 */
package org.eclipse.xtext.botlib.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BotDuinoAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/xtext/botlib/dsl/parser/antlr/internal/InternalBotDuino.tokens");
	}
}
