/*
 * generated by Xtext
 */
package org.eclipse.xtext.botlib.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.xtext.botlib.dsl.ui.internal.BotDuinoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BotDuinoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BotDuinoActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BotDuinoActivator.getInstance().getInjector(BotDuinoActivator.ORG_ECLIPSE_XTEXT_BOTLIB_DSL_BOTDUINO);
	}
	
}
