/*
 * generated by Xtext
 */
package org.eclipse.xtext.botlib.dsl.ui.contentassist

import org.eclipse.xtext.botlib.dsl.ui.contentassist.AbstractBotDuinoProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class BotDuinoProposalProvider extends AbstractBotDuinoProposalProvider {
}
