/*
 * generated by Xtext
 */
package org.eclipse.xtext.botlib.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.botlib.dsl.services.BotDuinoGrammarAccess;

public class BotDuinoParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BotDuinoGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.xtext.botlib.dsl.parser.antlr.internal.InternalBotDuinoParser createParser(XtextTokenStream stream) {
		return new org.eclipse.xtext.botlib.dsl.parser.antlr.internal.InternalBotDuinoParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}
	
	public BotDuinoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BotDuinoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
