/**
 * generated by Xtext
 */
package org.eclipse.xtext.botlib.dsl.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class BotDuinoQuickfixProvider extends XbaseQuickfixProvider {
}
