/*
 * generated by Xtext
 */
package org.eclipse.xtext.botlib.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BotDuinoUiModule extends org.eclipse.xtext.botlib.dsl.ui.AbstractBotDuinoUiModule {
	public BotDuinoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
