/**
 * generated by Xtext
 */
package org.eclipse.xtext.botlib.dsl.validation;

import org.eclipse.xtext.botlib.dsl.validation.AbstractBotDuinoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BotDuinoValidator extends AbstractBotDuinoValidator {
}
