/*
 * generated by Xtext
 */
package org.eclipse.xtext.botlib.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BotDuinoStandaloneSetup extends BotDuinoStandaloneSetupGenerated{

	public static void doSetup() {
		new BotDuinoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

